package rw.terimbere.csams.modules.report.export;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;
import rw.terimbere.csams.modules.report.dto.ReportHeaderMeta;
import rw.terimbere.csams.modules.report.dto.ReportSheetData;

/**
 * Landscape PDF report with header metadata, tabular sections, and totals.
 */
public final class PdfReportWriter {

    private static final DateTimeFormatter DATE_TIME =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss 'UTC'").withZone(ZoneOffset.UTC);
    private static final DateTimeFormatter DATE = DateTimeFormatter.ISO_LOCAL_DATE;
    private static final Color BRAND_BLUE = new Color(21, 101, 192);
    private static final Color HEADER_BG = new Color(21, 101, 192);
    private static final Color ZEBRA = new Color(245, 247, 250);
    private static final Color TOTALS_BG = new Color(232, 240, 248);

    private PdfReportWriter() {}

    public static byte[] write(ReportHeaderMeta header, List<ReportSheetData> sheets) {
        Document document = new Document(PageSize.A4.rotate(), 36, 36, 36, 36);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter.getInstance(document, out);
            document.open();
            writeHeader(document, header);

            if (sheets == null || sheets.isEmpty()) {
                document.add(body("No records for selected filters"));
            } else {
                for (ReportSheetData sheetData : sheets) {
                    document.add(sectionTitle(sheetData.getSheetName()));
                    document.add(buildTable(sheetData));
                }
            }

            document.close();
            return out.toByteArray();
        } catch (Exception ex) {
            throw new IllegalStateException("Failed to build PDF report", ex);
        } finally {
            if (document.isOpen()) {
                try {
                    document.close();
                } catch (Exception ignored) {
                    // Prefer the original exception from the try block.
                }
            }
        }
    }

    private static void writeHeader(Document document, ReportHeaderMeta header) throws DocumentException {
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, BRAND_BLUE);
        Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, Color.DARK_GRAY);
        Font valueFont = FontFactory.getFont(FontFactory.HELVETICA, 9, Color.BLACK);

        Paragraph title = new Paragraph(pdfText(header.getReportTitle(), "Report"), titleFont);
        title.setSpacingAfter(8);
        document.add(title);

        PdfPTable meta = new PdfPTable(4);
        meta.setWidthPercentage(100);
        meta.setSpacingAfter(14);
        meta.setWidths(new float[] {1.2f, 2.2f, 1.2f, 2.2f});

        addMeta(meta, "Cooperative", header.getCooperativeName(), labelFont, valueFont);
        addMeta(meta, "Selected period", header.getSelectedPeriod(), labelFont, valueFont);
        addMeta(
                meta,
                "Generated date",
                header.getGeneratedAt() == null ? "" : DATE_TIME.format(header.getGeneratedAt()),
                labelFont,
                valueFont);
        addMeta(meta, "Generated by", header.getGeneratedBy(), labelFont, valueFont);
        addMeta(meta, "Currency", header.getCurrency(), labelFont, valueFont);
        addMeta(meta, "Format", "PDF", labelFont, valueFont);
        document.add(meta);
    }

    private static void addMeta(PdfPTable table, String label, String value, Font labelFont, Font valueFont) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, labelFont));
        labelCell.setBorder(0);
        labelCell.setPadding(3);
        table.addCell(labelCell);

        PdfPCell valueCell = new PdfPCell(new Phrase(pdfText(value, ""), valueFont));
        valueCell.setBorder(0);
        valueCell.setPadding(3);
        table.addCell(valueCell);
    }

    private static Paragraph sectionTitle(String name) {
        Font font = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BRAND_BLUE);
        Paragraph paragraph = new Paragraph(pdfText(name, "Data"), font);
        paragraph.setSpacingBefore(6);
        paragraph.setSpacingAfter(6);
        return paragraph;
    }

    private static Paragraph body(String text) {
        Paragraph paragraph = new Paragraph(text, FontFactory.getFont(FontFactory.HELVETICA, 10, Color.DARK_GRAY));
        paragraph.setSpacingBefore(8);
        return paragraph;
    }

    private static PdfPTable buildTable(ReportSheetData data) {
        List<String> headers = data.getHeaders() == null ? List.of() : data.getHeaders();
        int columns = Math.max(1, headers.size());
        PdfPTable table = new PdfPTable(columns);
        table.setWidthPercentage(100);
        table.setHeaderRows(1);
        table.setSpacingAfter(12);

        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8, Color.WHITE);
        Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 8, Color.BLACK);
        Font totalFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8, Color.BLACK);

        if (headers.isEmpty()) {
            table.addCell(headerCell("Value", headerFont));
        } else {
            for (String heading : headers) {
                table.addCell(headerCell(heading, headerFont));
            }
        }

        List<List<Object>> rows = data.getRows() == null ? List.of() : data.getRows();
        if (rows.isEmpty()) {
            PdfPCell empty = bodyCell("No records for selected filters", cellFont, false);
            empty.setColspan(columns);
            table.addCell(empty);
        } else {
            int rowIdx = 0;
            for (List<Object> values : rows) {
                boolean zebra = rowIdx++ % 2 == 1;
                for (int i = 0; i < columns; i++) {
                    Object value = values != null && i < values.size() ? values.get(i) : null;
                    table.addCell(bodyCell(formatValue(value), cellFont, zebra));
                }
            }
        }

        if (data.getTotalsRow() != null && !data.getTotalsRow().isEmpty()) {
            for (int i = 0; i < columns; i++) {
                Object value = i < data.getTotalsRow().size() ? data.getTotalsRow().get(i) : null;
                PdfPCell cell = bodyCell(formatValue(value), totalFont, false);
                cell.setBackgroundColor(TOTALS_BG);
                table.addCell(cell);
            }
        }

        return table;
    }

    private static PdfPCell headerCell(String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(pdfText(text, ""), font));
        cell.setBackgroundColor(HEADER_BG);
        cell.setPadding(5);
        cell.setHorizontalAlignment(Element.ALIGN_LEFT);
        cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        return cell;
    }

    private static PdfPCell bodyCell(String text, Font font, boolean zebra) {
        PdfPCell cell = new PdfPCell(new Phrase(pdfText(text, ""), font));
        cell.setPadding(4);
        cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        if (zebra) {
            cell.setBackgroundColor(ZEBRA);
        }
        return cell;
    }

    private static String formatValue(Object value) {
        if (value == null) {
            return "";
        }
        if (value instanceof BigDecimal bd) {
            return bd.stripTrailingZeros().toPlainString();
        }
        if (value instanceof Number number) {
            return String.valueOf(number);
        }
        if (value instanceof LocalDate date) {
            return DATE.format(date);
        }
        if (value instanceof Instant instant) {
            return DATE_TIME.format(instant);
        }
        if (value instanceof Boolean bool) {
            return bool ? "Yes" : "No";
        }
        return pdfText(String.valueOf(value), "");
    }

    /**
     * Helvetica is WinAnsi-only. Unknown characters throw on some JREs (e.g. Alpine on Render).
     */
    private static String pdfText(String text, String blankFallback) {
        if (text == null || text.isBlank()) {
            return blankFallback == null ? "" : blankFallback;
        }
        String normalized = text
                .replace('\u2018', '\'')
                .replace('\u2019', '\'')
                .replace('\u201C', '"')
                .replace('\u201D', '"')
                .replace('\u2013', '-')
                .replace('\u2014', '-')
                .replace('\u00A0', ' ');
        StringBuilder safe = new StringBuilder(normalized.length());
        for (int i = 0; i < normalized.length(); i++) {
            char ch = normalized.charAt(i);
            if (ch == '\n' || ch == '\r' || ch == '\t') {
                safe.append(' ');
            } else if (ch == ' ' || ch == '\'' || ch == '"' || (ch >= 0x20 && ch <= 0x7E) || (ch >= 0xA0 && ch <= 0xFF)) {
                safe.append(ch);
            } else {
                safe.append('?');
            }
        }
        return safe.toString();
    }
}
