/** Auth feature surface — login UI lives in pages/; API + slice wired for Phase 2. */
export {
  changePassword,
  confirmPasswordReset,
  fetchMe,
  login,
  loginRequest,
  logout,
  refresh,
  requestPasswordReset,
  signup,
  unwrapApiData,
  updateMe,
} from '@/shared/api/auth'
export {
  clearAuth,
  selectAccessToken,
  selectAuthStatus,
  selectAuthUser,
  selectIsAuthenticated,
  selectIsCooperativeAdmin,
  selectIsLeadership,
  selectIsSuperAdmin,
  selectCanApproveLoans,
  selectCanAuthorizeFunds,
  selectCanManageMembers,
  selectCanPreparePayouts,
  selectCanRecordContributions,
  selectCanWriteSocial,
  selectCanRecordLoans,
  selectCanManageFineSettings,
  selectSelectedCooperativeId,
  selectUserRoles,
  setAuthStatus,
  setCredentials,
  setSelectedCooperativeId,
} from '@/app/store/authSlice'
