export const ROUTES = {
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  changePassword: '/change-password',
  dashboard: '/dashboard',
  members: '/members',
  memberDetail: (userId: string) => `/members/${userId}`,
  contributions: '/contributions',
  specialCampaign: (campaignId: string) => `/contributions/special/${campaignId}`,
  loans: '/loans',
  loanDetail: (loanId: string) => `/loans/${loanId}`,
  fines: '/fines',
  fineDetail: (fineId: string) => `/fines/${fineId}`,
  finePayments: '/fine-payments',
  socialFund: '/social-fund',
  investments: '/investments',
  investmentDetail: (investmentId: string) => `/investments/${investmentId}`,
  transactions: '/transactions',
  ledger: '/ledger',
  payouts: '/payouts',
  payoutDetail: (runId: string) => `/payouts/${runId}`,
  reports: '/reports',
  settings: '/settings',
  notifications: '/notifications',
  auditLogs: '/audit-logs',
  profile: '/profile',
  cooperatives: '/cooperatives',
  cooperativeDetail: (id: string) => `/cooperatives/${id}`,
  system: '/system',
} as const

export type AppRoute = Exclude<(typeof ROUTES)[keyof typeof ROUTES], (...args: never[]) => string>
