package rw.terimbere.csams.shared.financial;

public enum LedgerTransactionType {
    REGULAR_CONTRIBUTION,
    SPECIAL_CONTRIBUTION,
    LOAN_DISBURSEMENT,
    LOAN_PRINCIPAL_REPAYMENT,
    LOAN_INTEREST_PAYMENT,
    FINE_PAYMENT,
    SOCIAL_CONTRIBUTION,
    SOCIAL_DISBURSEMENT,
    INVESTMENT_OUTFLOW,
    INVESTMENT_CAPITAL_RETURN,
    INVESTMENT_PROFIT,
    OTHER_INCOME,
    GENERAL_EXPENSE,
    INTEREST_EXPENSE,
    MEMBER_PAYOUT,
    ADJUSTMENT,
    REVERSAL
}
